CREATE TABLE [dbo].[st_salesAgencyCostCentre] (
    [salesAgencyCostCentreUuid]         VARCHAR (100) NOT NULL,
    [code]                              VARCHAR (100) NULL,
    [name]                              VARCHAR (100) NULL,
    [description]                       VARCHAR (100) NULL,
    [companyUuid]                       VARCHAR (100) NOT NULL,
    [startDate]                         DATETIME      NULL,
    [endDate]                           DATETIME      NULL,
    [status]                            VARCHAR (100) NULL,
    [currentCustodianFirstName]         VARCHAR (100) NULL,
    [currentCustodianLastName]          VARCHAR (100) NULL,
    [currentCustodianUuid]              VARCHAR (100) NOT NULL,
    [detailedDescription]               VARCHAR (100) NULL,
    [reason]                            VARCHAR (100) NULL,
    [omsMappingValidationMessage]       VARCHAR (100) NULL,
    [custodianLinkEndDate]              DATETIME      NULL,
    [costCentreCustodianLinksUuid]      VARCHAR (100) NOT NULL,
    [companyUserUuid]                   VARCHAR (100) NOT NULL,
    [costCentreCustodianLinksStatus]    VARCHAR (10)  NULL,
    [contractedHours]                   INT           NULL,
    [effectiveFromDate]                 DATETIME      NULL,
    [effectiveToDate]                   DATETIME      NULL,
    [userUuid]                          VARCHAR (100) NOT NULL,
    [username]                          VARCHAR (100) NULL,
    [firstName]                         VARCHAR (100) NULL,
    [lastName]                          VARCHAR (100) NULL,
    [emailAddress]                      VARCHAR (100) NULL,
    [identityNumber]                    BIGINT        NULL,
    [admin]                             VARCHAR (100) NULL,
    [availableForSelection]             VARCHAR (100) NULL,
    [costCentreCustodianLinksReason]    VARCHAR (100) NULL,
    [costCentreCustodianLinksStartDate] DATETIME      NULL,
    [costCentreCustodianLinksEndDate]   DATETIME      NULL,
    [loadDate]                          DATETIME      NULL,
    CONSTRAINT [PK_st_salesAgencyCostCentre] PRIMARY KEY CLUSTERED ([salesAgencyCostCentreUuid] ASC)
);

