CREATE TABLE [dbo].[st_taskTracker] (
    [Domain]                    VARCHAR (8)   NULL,
    [KeyCustomer]               INT           NULL,
    [taskInstanceUuid]          VARCHAR (100) NULL,
    [appointmentTypeUuid]       VARCHAR (100) NULL,
    [scheduleType]              VARCHAR (50)  NULL,
    [KeyscheduleType]           INT           NULL,
    [appointmentDate]           DATETIME      NULL,
    [KeyappointmentDate]        INT           NULL,
    [startTime]                 TIME (0)      NULL,
    [KeystartTime]              INT           NULL,
    [endTime]                   TIME (0)      NULL,
    [KeyendTime]                INT           NULL,
    [UserUuid]                  VARCHAR (100) NULL,
    [companyUserUuid]           VARCHAR (100) NULL,
    [customerLocationUuid]      VARCHAR (100) NULL,
    [customerAccountUuid]       VARCHAR (100) NULL,
    [tradeChannelUuid]          VARCHAR (100) NULL,
    [principalUuid]             VARCHAR (100) NULL,
    [serviceProviderUuid]       VARCHAR (100) NULL,
    [salesAgencyCostCentreUuid] VARCHAR (100) NULL,
    [taskUuid]                  VARCHAR (100) NULL,
    [status]                    VARCHAR (100) NULL,
    [KeytaskStatus]             INT           NULL,
    [completedDateTime]         DATETIME      NULL,
    [KeycompletedDate]          INT           NULL,
    [KeycompletedTime]          INT           NULL,
    [externalSystemDataKey]     VARCHAR (100) NULL,
    [taskTypeUuid]              VARCHAR (100) NULL,
    [loadDate]                  DATETIME      NULL
);

